In [1]:
# Source:https://www.kaggle.com/datasets/vstacknocopyright/magic-telescope-dataset
import pandas as pd
import numpy as np
df = pd.read_csv("MagicTelescope.csv")
df.head()

,id,ID,fLength:,fWidth:,fSize:,fConc:,fConc1:,fAsym:,fM3Long:,fM3Trans:,fAlpha:,fDist:,class:
0,1,1,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,2,2,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,3,3,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,4,4,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,5,5,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g

In [2]:
rows,columns = df.shape

print("Количество строк:",rows)
print("Количество столбцов:",columns)

Количество строк: 19020
Количество столбцов: 13

In [12]:
describe1 = df.describe()
describe1

,id,ID,fLength:,fWidth:,fSize:,fConc:,fConc1:,fAsym:,fM3Long:,fM3Trans:,fAlpha:,fDist:
count,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000,19020.000000
mean,9510.500000,9510.500000,53.250154,22.180966,2.825017,0.380327,0.214657,-4.331745,10.545545,0.249726,27.645707,193.818026
std,5490.745396,5490.745396,42.364855,18.346056,0.472599,0.182813,0.110511,59.206062,51.000118,20.827439,26.103621,74.731787
min,1.000000,1.000000,4.283500,0.000000,1.941300,0.013100,0.000300,-457.916100,-331.780000,-205.894700,0.000000,1.282600
25%,4755.750000,4755.750000,24.336000,11.863800,2.477100,0.235800,0.128475,-20.586550,-12.842775,-10.849375,5.547925,142.492250
50%,9510.500000,9510.500000,37.147700,17.139900,2.739600,0.354150,0.196500,4.013050,15.314100,0.666200,17.679500,191.851450
75%,14265.250000,14265.250000,70.122175,24.739475,3.101600,0.503700,0.285225,24.063700,35.837800,10.946425,45.883550,240.563825
max,19020.000000,19020.000000,334.177000,256.382000,5.323300,0.893000,0.675200,575.240700,238.321000,179.851000,90.000000,495.561000

In [22]:
describe2 = np.around(describe1, decimals=2, out=None)
describe2

,id,ID,fLength:,fWidth:,fSize:,fConc:,fConc1:,fAsym:,fM3Long:,fM3Trans:,fAlpha:,fDist:
count,19020.00,19020.00,19020.00,19020.00,19020.00,19020.00,19020.00,19020.00,19020.00,19020.00,19020.00,19020.00
mean,9510.50,9510.50,53.25,22.18,2.83,0.38,0.21,-4.33,10.55,0.25,27.65,193.82
std,5490.75,5490.75,42.36,18.35,0.47,0.18,0.11,59.21,51.00,20.83,26.10,74.73
min,1.00,1.00,4.28,0.00,1.94,0.01,0.00,-457.92,-331.78,-205.89,0.00,1.28
25%,4755.75,4755.75,24.34,11.86,2.48,0.24,0.13,-20.59,-12.84,-10.85,5.55,142.49
50%,9510.50,9510.50,37.15,17.14,2.74,0.35,0.20,4.01,15.31,0.67,17.68,191.85
75%,14265.25,14265.25,70.12,24.74,3.10,0.50,0.29,24.06,35.84,10.95,45.88,240.56
max,19020.00,19020.00,334.18,256.38,5.32,0.89,0.68,575.24,238.32,179.85,90.00,495.56